---
# tasks file for vm_hardening
- block:
  - include_tasks: task_check_con_creds.yml
  - block:
    - include_tasks: task_enable_hardening.yml
    - include_tasks: task_update_iptables.yml
    - name: flush handlers
      meta: flush_handlers
    when: hardv | default(true) | bool
  - include_tasks: task_root_never_expire.yml
  when: harden_vms | default(false) | bool
  tags: vm_hardening
