---
# Tasks to delete the downloaded hardening roles
- name: Deleting the downloaded roles
  delegate_to: localhost
  run_once: true
  block:
    - name: Get the list of the downloaded roles
      ansible.builtin.shell:
        cmd: set -o pipefail && grep src requirements.yml
        executable: /bin/bash
      args:
        chdir: "{{ auto_dir }}/roles/{{ hardening_reponame }}"
      register: reg_harden_roles
      changed_when: false
    - name: Define list of downloaded roles
      ansible.builtin.set_fact:
        downloaded_roles_list: "{{ downloaded_roles_list | default([hardening_reponame]) | union([role_item | split('/') | last | replace('.git', '')]) }}"
      loop: "{{ reg_harden_roles.stdout_lines }}"
      loop_control:
        loop_var: role_item
    - name: Delete downloaded roles
      ansible.builtin.file:
        path: "{{ auto_dir }}/roles/{{ role_item }}"
        state: absent
      loop: "{{ downloaded_roles_list }}"
      loop_control:
        loop_var: role_item
      become: true
