---
# tasks to update iptables on VM
- block:
  - name: update iptables
    iptables:
      chain: INPUT
      protocol: udp
      destination_port: "{{ port_item }}"
      jump: ACCEPT
    loop:
      - 161
    loop_control:
      loop_var: port_item
    notify:
      - save iptables
      - restart iptables
  become: "{{ true if ansible_user != 'root' else false }}"
  when: not ansible_check_mode
  tags: vm_hardening
