---
# Variables for standalone VMs
credentials:
  username: "{{ PLINUX_SUPERUSER_USER | default('') }}"
  password: "{{ PLINUX_SUPERUSER_PASS | default('') }}"

user:
  name: "{{ vm_vars.lnxvm.user.name if vm_vars.lnxvm.user.name is defined else '' }}"
  password: "{{ vm_vars.lnxvm.user.password if vm_vars.lnxvm.user.password is defined else '' }}"

vm:
  cpu: "{{ vm_vars.lnxvm.cpu }}"
  memory: "{{ vm_vars.lnxvm.memory }}"
  disk0: "{{ vm_vars.lnxvm.disk0 }}"
  disk1: "{{ vm_vars.lnxvm.disk1 | default(0) }}"
  disk2: "{{ vm_vars.lnxvm.disk2 | default(0) }}"
  disk3: "{{ vm_vars.lnxvm.disk3 | default(0) }}"
  disk1_mount: "{{ vm_vars.lnxvm.disk1_mount | default('/opt') }}"
  disk2_mount: "{{ vm_vars.lnxvm.disk2_mount | default('/data01') }}"
  disk3_mount: "{{ vm_vars.lnxvm.disk3_mount | default('/data02') }}"
  disk_provisioning: "{{ vm_vars.lnxvm.disk_provisioning if vm_vars.lnxvm.disk_provisioning != '' else '' }}"
  hostmap: "{{ vm_vars.lnxvm.hostmap | default([]) }}"
  name: "{{ vm_vars.lnxvm.vmname if vm_vars.lnxvm.vmname != '' else (build.primary.name_prefix + inventory_hostname[-2:]) }}"

netconfig:
  nic1:
    intname: "{{ vm_vars.lnxvm.nic1.intname }}"
    ippool: "{{ vm_vars.lnxvm.nic1.ip_pool | default([]) }}"
    octetpool: "{{ vm_vars.lnxvm.nic1.ip_octetpool | default([]) }}"
    gateway: "{{ vm_vars.lnxvm.nic1.gtw if vm_vars.lnxvm.nic1.gtw != '' else (build.primary.octets + '.' + vm_vars.lnxvm.nic1.gtw_octet) if vm_vars.lnxvm.nic1.gtw_octet != '' else '' }}" # noqa: yaml[line-length]
    netmask: "{{ vm_vars.lnxvm.nic1.netmask }}"
    network: "{{ vm_vars.lnxvm.nic1.netname if vm_vars.lnxvm.nic1.netname != '' else (build.primary.name_prefix + '-' + vm_vars.lnxvm.nic1.netbase) if vm_vars.lnxvm.nic1.netbase != '' else '' }}" # noqa: yaml[line-length]
    ipv6_pool: "{{ vm_vars.lnxvm.nic1.ipv6_pool | default([]) }}"
    ipv6_gtw: "{{ vm_vars.lnxvm.nic1.ipv6_gtw | default('') }}"

  nic2:
    intname: "{{ vm_vars.lnxvm.nic2.intname }}"
    ippool: "{{ vm_vars.lnxvm.nic2.ip_pool | default([]) }}"
    octetpool: "{{ vm_vars.lnxvm.nic2.ip_octetpool | default([]) }}"
    gateway: "{{ vm_vars.lnxvm.nic2.gtw if vm_vars.lnxvm.nic2.gtw != '' else (build.primary.octets + '.' + vm_vars.lnxvm.nic2.gtw_octet) if vm_vars.lnxvm.nic2.gtw_octet != '' else '' }}" # noqa: yaml[line-length]
    netmask: "{{ vm_vars.lnxvm.nic2.netmask }}"
    network: "{{ vm_vars.lnxvm.nic2.netname if vm_vars.lnxvm.nic2.netname != '' else (build.primary.name_prefix + '-' + vm_vars.lnxvm.nic2.netbase) if vm_vars.lnxvm.nic2.netbase != '' else '' }}" # noqa: yaml[line-length]
    ipv6_pool: "{{ vm_vars.lnxvm.nic2.ipv6_pool | default([]) }}"
    ipv6_gtw: "{{ vm_vars.lnxvm.nic2.ipv6_gtw | default('') }}"
