---
# handlers file for vm_configuration
- name: restart sshd service
  systemd:
    name: sshd
    state: restarted
    daemon_reload: yes
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_configuration
