---
# handlers file for vm_configuration
- name: Restart sshd service
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: true
  become: "{{ true if ansible_user != 'root' else false }}"
