---
# tasks file for roles/devsim
- block:
  - name: check original credentials
    block:
      - name: check VM credentials
        ansible.builtin.wait_for_connection:
          timeout: 3
        register: dvsm_vm_creds
        check_mode: no
    rescue:
      - name: define creds_status
        ansible.builtin.set_fact:
          creds_status: 'The VM IP address is invalid'
        when:
          - dvsm_vm_creds.msg is search('Failed to connect to the host via ssh')
      - block:
        - name: check service account credentials
          block:
            - name: Switch to {{ vm_admin_user }} user
              ansible.builtin.set_fact:
                ansible_user: "{{ vm_admin_user }}"
                ansible_ssh_pass: "{{ vm_admin_pass }}"
                ansible_become_pass: "{{ vm_admin_pass }}"
              no_log: true
            - name: check updated VM credentials
              ansible.builtin.wait_for_connection:
                timeout: 3
              check_mode: no
          rescue:
            - name: define creds_status
              ansible.builtin.set_fact:
                creds_status: 'The VM credentials are invalid'
        when:
          - dvsm_vm_creds.msg is search('Invalid/incorrect')
  - ansible.builtin.assert:
      that:
        - creds_status|default('') is not search('invalid')
      fail_msg: "{{ creds_status|default('') }}"
  - include_tasks: task_check_devsim.yml
    when: check_devsim|default(false)|bool
  - include_tasks: task_start_devsim.yml
    when: deploy_devsim|default(false)|bool or start_devsim|default(false)|bool
  - include_tasks: task_stop_devsim.yml
    when: rollback_devsim|default(false)|bool or stop_devsim|default(false)|bool
  tags: [ 'never', 'devsim' ]
