---
# tasks file for roles/devsim
- block:
  - name: check original credentials
    block:
      - name: check VM credentials
        wait_for_connection:
          timeout: 3
        register: dvsm_vm_creds
        check_mode: no
    rescue:
      - name: define creds_status
        ansible.builtin.set_fact:
          creds_status: 'The VM IP address is invalid'
        when:
          - dvsm_vm_creds.msg is search('Failed to connect to the host via ssh')
      - block:
        - name: check service account credentials
          block:
            - name: Switch to {{ vm_svc_user }} user
              set_fact:
                ansible_user: "{{ vm_svc_user }}"
                ansible_ssh_pass: "{{ vm_svc_pass }}"
                ansible_become_pass: "{{ vm_svc_pass }}"
              no_log: true
            - name: check updated VM credentials
              wait_for_connection:
                timeout: 3
              check_mode: no
          rescue:
            - name: define creds_status
              ansible.builtin.set_fact:
                creds_status: 'The VM credentials are invalid'
        when:
          - dvsm_vm_creds.msg is search('Invalid/incorrect')
  - assert:
      that:
        - creds_status | default('') is not search('invalid')
      fail_msg: "{{ creds_status | default('') }}"
  - include_tasks: task_get_avmid_lists.yml
  - include_tasks: task_start_devsim.yml
    when: start_devsim | default(false) | bool
  - include_tasks: task_stop_devsim.yml
    when: stop_devsim | default(false) | bool
  - debug:
      msg:
        - 'The following AVM IDs do not correspond to AVM files'
        - "{{ bad_avmid_list|join(',') }}"
    when:
      - not check_devsim | default(false) | bool
      - bad_avmid_list != []
  tags: [ 'never', 'devsim' ]
