---
# tasks file for roles/devsim
- name: Main devsim block
  tags: ['never', 'devsim']
  block:
    - name: Checking if VM exists
      block:
        - name: Check if VM exists
          community.vmware.vmware_guest_info:
            hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
            username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
            password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
            datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
            name: "{{ vm.name }}"
            schema: vsphere
            validate_certs: false
          no_log: true
          delegate_to: localhost
      rescue:
        - name: Define creds_status
          ansible.builtin.set_fact:
            creds_status: 'The VM does not exist'
    - name: Check original credentials
      when:
        - creds_status | default('') == ''
      block:
        - name: Check VM credentials
          ansible.builtin.wait_for_connection:
            timeout: 3
          register: dvsm_vm_creds
          check_mode: false
      rescue:
        - name: Define creds_status
          ansible.builtin.set_fact:
            creds_status: 'The VM IP address is invalid'
          when:
            - dvsm_vm_creds.msg is defined
            - dvsm_vm_creds.msg is search('Failed to connect to the host via ssh|Data could not be sent to remote host')
        - name: Check service account credentials
          when:
            - dvsm_vm_creds.msg is defined
            - dvsm_vm_creds.msg is search('Invalid/incorrect')
          block:
            - name: Switch to {{ vm_admin_user + ' user' }}
              ansible.builtin.set_fact:
                ansible_user: "{{ vm_admin_user }}"
                ansible_ssh_pass: "{{ vm_admin_pass }}"
                ansible_become_pass: "{{ vm_admin_pass }}"
              no_log: true
            - name: Check updated VM credentials
              ansible.builtin.wait_for_connection:
                timeout: 3
              check_mode: false
          rescue:
            - name: Define creds_status
              ansible.builtin.set_fact:
                creds_status: 'The VM credentials are invalid'
    - name: Assert that credentials are valid and that VM exists
      ansible.builtin.assert:
        that:
          - creds_status | default('') is not search('invalid')
          - creds_status | default('') is not search('does not exist')
        fail_msg: "{{ creds_status | default('') }}"
    - name: Check devsim
      ansible.builtin.include_tasks: task_check_devsim.yml
      when: check_devsim | default(false) | bool
    - name: Start devsim
      ansible.builtin.include_tasks: task_start_devsim.yml
      when: deploy_devsim | default(false) | bool or start_devsim | default(false) | bool
    - name: Stop devsim
      ansible.builtin.include_tasks: task_stop_devsim.yml
      when: rollback_devsim | default(false) | bool or stop_devsim | default(false) | bool
