---
# tasks to get the avmid lists
- block:
  - include_tasks: task_get_file_avmid.yml
  - block:
    - block:
      - include_tasks: task_get_active_avmid.yml
      - name: define avmid lists
        ansible.builtin.set_fact:
          good_avmid_list: "{{ file_avmid_list | community.general.lists_difference(active_avmid_list)|map('int')|sort|map('string') }}"
          bad_avmid_list: []
      when: AVMLIST|default('') == ''
    - name: define avmid lists
      ansible.builtin.set_fact:
        good_avmid_list: "{{ AVMLIST|split(',')|list | community.general.lists_intersect(file_avmid_list)|map('int')|sort|map('string') }}"
        bad_avmid_list: "{{ AVMLIST|split(',')|list | community.general.lists_difference(file_avmid_list)|map('int')|sort|map('string') }}"
      when: AVMLIST|default('') != ''
    when:
      - file_avmid_list != []
