---
# tasks to start device simulation
- block:
  - include_tasks:
      file: task_manage_avm.yml
      apply:
        vars:
          avm_id: "{{ id_item }}"
          avm_action: 'start'
    loop: "{{ good_avmid_list }}"
    loop_control:
      loop_var: id_item
  tags: [ 'never', 'devsim' ]
