---
# tasks to delete dummy interface
- name: delete dummy interface
  ansible.builtin.command: nmcli connection delete {{ int_id }}
  register: reg_del_int
  until: reg_del_int is succeeded
#  community.general.nmcli:
#    conn_name: "{{ int_id }}"
#    state: absent
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'devsim' ]
