---
# tasks to delete dummy interface
- name: delete dummy{{ int_id }} interface
  community.general.nmcli:
    conn_name: "dummy{{ int_id }}"
    state: absent
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'devsim' ]
