---
# tasks to get the list of active AVM IDs
- name: Getting the list of active AVM IDs
  block:
    - name: Find active AVM file IDs
      ansible.builtin.shell:
        cmd: set -o pipefail && ps -ef | grep AVM | grep -v grep | awk '{print $18}'
        executable: /bin/bash
      register: reg_active
      changed_when: false
      check_mode: false
    - name: Define active_avmid_list
      ansible.builtin.set_fact:
        active_avmid_list: "{{ reg_active.stdout_lines | map('int') | sort | map('string') }}"
  rescue:
    - name: Reboot the VM
      ansible.builtin.reboot:
      when: reg_active.stderr is search('Cannot allocate memory')
      become: "{{ true if ansible_user != 'root' else false }}"
    - name: Find active AVM file IDs
      ansible.builtin.shell:
        cmd: set -o pipefail && ps -ef | grep AVM | grep -v grep | awk '{print $18}'
        executable: /bin/bash
      register: reg_active
      changed_when: false
      check_mode: false
    - name: Define active_avmid_list
      ansible.builtin.set_fact:
        active_avmid_list: "{{ reg_active.stdout_lines | map('int') | sort | map('string') }}"
