---
# tasks file to get the list of AVM files IDs
- block:
  - name: find all AVM files
    ansible.builtin.find:
      paths: "/opt/{{ automation_reponame }}/simulator/registry"
      patterns: 'avm*.xml'
    register: reg_avm_files
    no_log: true
  - name: define file_avmid_list
    ansible.builtin.set_fact:
      file_avmid_list: "{{ file_avmid_list|default([]) | union([file_item.path|regex_replace('^.*avm(.*).xml$','\\1')]) }}"
    loop: "{{ reg_avm_files.files }}"
    loop_control:
      loop_var: file_item
      label: "{{ file_item.path }}"
  tags: [ 'never', 'devsim' ]
