---
# tasks to get the avmid lists
- block:
  - include_tasks: task_get_active_avmid.yml
  - name: define avmid lists
    ansible.builtin.set_fact:
      good_avmid_list: "{{ active_avmid_list|map('int')|sort|map('string') }}"
      bad_avmid_list: []
    when: AVMLIST|default('') == ''
  - name: define avmid lists
    ansible.builtin.set_fact:
      good_avmid_list: "{{ AVMLIST|split(',')|list | intersect(active_avmid_list)|map('int')|sort|map('string') }}"
      bad_avmid_list: "{{ AVMLIST|split(',')|list | difference(active_avmid_list)|map('int')|sort|map('string') }}"
    when: AVMLIST|default('') != ''
  tags: [ 'never', 'devsim' ]
