---
# tasks to stop AVM simulation
- block:
  - name: stop AVM {{ avm_id }}
    ansible.builtin.shell:
      kill -9 $(ps -ef | grep "AVM -a {{ avm_id }}" | grep -v grep | awk '{print $2}')
    register: reg_stop
    become: "{{ true if ansible_user != 'root' else false }}"
  rescue:
  - debug:
      msg: "{{ reg_stop }}"
  tags: [ 'never', 'devsim' ]
