---
# tasks file to get the list of AVM files IDs
- name: Find all AVM files
  ansible.builtin.shell:
    cmd: set -o pipefail && ls avm*.xml | sed 's/^avm\(.*\)\.xml$/\1/g'
    executable: /bin/bash
    chdir: "/opt/{{ automation_reponame }}/simulator/registry"
  register: reg_avm_files
  changed_when: false
  check_mode: false
- name: Define file_avmid_list
  ansible.builtin.set_fact:
    file_avmid_list: "{{ reg_avm_files.stdout_lines }}"
