---
# tasks to start device simulation
- block:
  - block:
    - include_tasks: task_get_avmid_lists.yml
    - include_tasks:
        file: task_start_device.yml
        apply:
          vars:
            avmid: "{{ id_item }}"
            avm_action: 'start'
      loop: "{{ good_avmid_list }}"
      loop_control:
        loop_var: id_item
    - ansible.builtin.debug:
        msg:
          - 'The following AVM IDs do not correspond to AVM files'
          - "{{ bad_avmid_list|join(',') }}"
      when:
        - bad_avmid_list != []
    when: start_devsim|default(false)|bool
  - block:
    - include_tasks:
        file: task_verify_device_info.yml
        apply:
          vars:
            device: "{{ device_item }}"
      when:
          - device_item.api
          - device_item.snmpv2 or device_item.snmpv3
      loop: "{{ device_list|default([]) }}"
      loop_control:
        loop_var: device_item
    - ansible.builtin.assert:
        that: devinfo_status|default([]) == []
        fail_msg: "{{ devinfo_status|default([]) }}"
    - include_tasks:
        file: task_simulate_device.yml
        apply:
          vars:
            device: "{{ device_item }}"
            avm_action: 'start'
      loop: "{{ device_list|default([]) }}"
      loop_control:
        loop_var: device_item
    when: deploy_devsim|default(false)|bool
  - name: display list of flawed SNMP recordings
    ansible.builtin.debug:
      msg:
        - "{{ snmp_flawed_recording_list|default([])|length|string + ' flawed files have been identified:' }}"
        - "{{ snmp_flawed_recording_list|default([]) }}"
    when: snmp_flawed_recording_list|default([]) != []
  tags: [ 'never', 'devsim' ]
