---
# tasks to verify SSH conection to device
- block:
  - name: verify ssh connection to device at {{ ip }}
    ansible.builtin.shell: |
      timeout 15s sshpass -p {{ password }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T {{ username }}@{{ ip }} <<EOF
      show version
      EOF
    register: reg_ssh
    until: reg_ssh is succeeded
    retries: 7
    failed_when:
      - (reg_ssh.rc != 0 and reg_ssh.rc != 6 and reg_ssh.rc != 124 and reg_ssh.rc != 255) or reg_ssh.stderr_lines|select('search', 'Connection (timed out|refused)|No route to host') != []
  check_mode: no
  delegate_to: localhost
