---
# tasks to get the first available AVM ID
- name: Define first_available_id
  ansible.builtin.set_fact:
    first_available_id: "{{ first_dummy_interface_id }}"
  when:
    - active_avmid_list == []
- name: Defining first available ID
  when:
    - active_avmid_list != []
  block:
    - name: Define first_available_id (increment last active ID)
      ansible.builtin.set_fact:
        first_available_id: "{{ active_avmid_list | last | int + 1 }}"
      when:
        - range(first_dummy_interface_id | int, active_avmid_list | last | int + 1) | \
          map('string') | community.general.lists_difference(active_avmid_list) == [] or device.num | int > 1
    - name: Define first ID
      when:
        - first_available_id | default(first_dummy_interface_id) | int < active_avmid_list | last | int
      block:
        - name: Define fid (defined)
          ansible.builtin.set_fact:
            fid: "{{ range(first_available_id | int + 1, active_avmid_list | last | int + 1) | \
              map('string') | community.general.lists_difference(active_avmid_list) | first }}"
          when:
            - first_available_id is defined
            - first_available_id != ''
            - fid | default('') == ''
        - name: Define fid (undefined)
          ansible.builtin.set_fact:
            fid: "{{ range(first_dummy_interface_id | int, active_avmid_list | last | int + 1) | \
              map('string') | community.general.lists_difference(active_avmid_list) | first }}"
          when:
            - first_available_id is not defined or first_available_id == ''
            - fid | default('') == ''
        - name: Define first_available_id (fid)
          ansible.builtin.set_fact:
            first_available_id: "{{ fid }}"
            fid: ''
          when:
            - fid is defined
            - fid != ''
