---
# tasks to start device simulation
- block:
  - include_tasks:
      file: task_manage_avm.yml
      apply:
        vars:
          device: "{{ device_item }}"
          avm_action: 'start'
    loop: "{{ device_list }}"
    loop_control:
      loop_var: device_item
  tags: [ 'never', 'devsim' ]
