---
# tasks to delete dummy interface
- name: Delete dummy{{ int_id + ' interface' }}
  ansible.builtin.command: ip link delete dummy{{ int_id }} type dummy
  register: delete_dummy
  changed_when: delete_dummy.rc == 0
  become: "{{ true if ansible_user != 'root' else false }}"
