---
# tasks to create dummy interface
- name: Create dummy{{ int_id + ' interface' }}
  ansible.builtin.shell: |
    ip link add dummy{{ int_id }} type dummy
    ip addr add 192.0.0.1/24 dev dummy{{ int_id }}
    ip link set up dummy{{ int_id }}
  register: create_dummy
  changed_when: create_dummy.rc == 0
  become: "{{ true if ansible_user != 'root' else false }}"
