---
# tasks to validate vcenter credentials
- name: Validating vcenter credentials
  block:
    - name: Validate {{ ('secondary' if vcenter_host is search('dr') else 'primary') + ' vcenter credentials' }}
      community.vmware.vmware_about_info:
        hostname: "{{ hostvars[vcenter_host]['information']['address'] }}"
        username: "{{ hostvars[vcenter_host]['credentials']['username'] }}"
        password: "{{ hostvars[vcenter_host]['credentials']['password'] }}"
        validate_certs: false
      register: vcenter_creds
      delegate_to: localhost
  rescue:
    - name: Define abort_play and err_msg
      ansible.builtin.set_fact:
        abort_play: true
        err_msg: "{{ vcenter_host }}: {{ vcenter_creds.msg }}"
