---
# Tasks for vm_facts
- block:
  - block:
    - name: get list of stack groups in play
      set_fact:
        play_stack_group_list: "{{ play_stack_group_list|default([]) | union([host_item[:-2]]) }}"
      loop: "{{ ansible_play_hosts | reject('search', 'dr|vcenter') | list }}"
      loop_control:
        loop_var: host_item
        label: "{{ host_item }}"
    - name: get list of DR groups in play
      set_fact:
        play_dr_group_list: "{{ play_dr_group_list|default([]) | union([host_item[:-2]]) }}"
      loop: "{{ ansible_play_hosts | select('match', 'dr') | reject('search', 'vcenter') | list }}"
      loop_control:
        loop_var: host_item
        label: "{{ host_item }}"
      when: build.disaster_recovery
    run_once: true
  - include_tasks: task_check_cluster_name.yml
  - block:
    - block:
      - include_tasks: task_define_vm_disk_size.yml
      - include_tasks: task_define_groups_list.yml
      when:
        - deploy | default(false)
    - include_tasks: task_define_vm_ip.yml
    when:
      - "'stack' in group_names or (build.disaster_recovery and 'dr' in group_names)"
  tags: ['always', 'vm_facts']
