---
# tasks file for vm_fromiso
- block:
  - include_tasks: task_delete_ssh_key.yml
  - include_tasks: task_define_folder_name.yml
  - block:
    - include_tasks: task_check_con_creds.yml
    - include_tasks: task_create_vms.yml
    when: create_vms_iso | default(false) | bool

  - include_tasks: task_rollback_vms.yml
    when: rollback_vms_iso | default(false) | bool
  tags: vm_creation
