---
# Tasks to create and configure VM pairs
- name: Get VM datastore
  ansible.builtin.include_tasks: task_get_vm_datastore.yml
  when:
    - hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datastore_cluster'] == '' or \
      hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['deptype'] == 'h'
- name: Deploying ISO self healing
  when:
    - crecon | default(true) | bool
    - "vcr_vm_reachable | default({'failed': true}) is skipped or vcr_vm_reachable | default({'failed': true}) is failed"
    - "vcr_vm_connection | default({'failed': true}) is skipped or vcr_vm_connection | default({'failed': true}) is failed"
  block:
    - name: Create kickstart ISO
      ansible.builtin.include_tasks: task_create_kickstart_iso.yml
    - name: Copy kickstart ISO to Vsphere
      ansible.builtin.include_tasks: task_copy_kickstart_iso_to_vsphere.yml
    - name: Deploy ISO self healing
      ansible.builtin.include_tasks: task_deploy_iso_self_healing.yml
- name: Update custom attributes
  ansible.builtin.include_tasks: task_update_custom_attributes.yml
- name: Delete NIC1 gateway self healing
  ansible.builtin.include_tasks: task_delete_gtw_nic1_self_healing.yml
- name: Update disks self healing
  ansible.builtin.include_tasks: task_update_disks_self_healing.yml
- name: Clean up and update network settings
  when:
    - crecon | default(true) | bool
    - "vcr_vm_reachable | default({'failed': true}) is skipped or vcr_vm_reachable | default({'failed': true}) is failed"
    - "vcr_vm_connection | default({'failed': true}) is skipped or vcr_vm_connection | default({'failed': true}) is failed"
  block:
    - name: Power off VM
      ansible.builtin.include_tasks: task_poweroff_vm.yml
    - name: Disconnect CDROM
      ansible.builtin.include_tasks: task_disconnect_cdrom.yml
    - name: Power on VM
      ansible.builtin.include_tasks: task_poweron_vm.yml
    - name: Delete Kickstart files
      ansible.builtin.include_tasks: task_delete_kickstart_files.yml
    - name: Update default route
      ansible.builtin.include_tasks: task_update_default_route.yml
    - name: Add gateway2
      ansible.builtin.include_tasks: task_add_gtw2.yml
    - name: Increase open files limit
      ansible.builtin.include_tasks: task_increase_open_files_limit.yml
- name: Fix disks order
  when:
    - vmguest_disk0 is changed or vmguest_disk1 is changed or vmguest_disk2 is changed or vmguest_disk3 is changed
    - disk_info.guest_disk_info | dict2items | length >= 2
  block:
    - name: Check disks order
      ansible.builtin.shell:
        cmd: set -o pipefail && df -h | grep /boot | awk '{print $1}'
        executable: /bin/bash
      register: reg_boot
      changed_when: false
      become: "{{ true if ansible_user != 'root' else false }}"
    - name: Reboot vm
      ansible.builtin.reboot:
        post_reboot_delay: 10
        reboot_timeout: 60
      when: reg_boot.stdout is not search('sda')
      become: "{{ true if ansible_user != 'root' else false }}"
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Increase max pid number
  ansible.builtin.include_tasks: task_increase_max_pid_number.yml
