---
# Tasks to create the kickstart ISO
- block:
  - name: Create kickstart cfg
    template:
      src: templates/kickstart.cfg.j2
      dest: "{{ role_path }}/files/{{ vm.name }}-kickstart.cfg"
  - name: Build kickstart iso
    command: python3.9 '{{ role_path }}/files/kickstart-iso.py' '{{ role_path }}/files/{{ vm.name }}-kickstart.cfg' '{{ role_path }}/files/{{ vm.name }}-kickstart.iso'
  delegate_to: localhost
  tags: vm_creation
