---
# Tasks to create the kickstart ISO
- name: Creating kickstart ISO
  delegate_to: localhost
  block:
    - name: Create kickstart cfg
      ansible.builtin.template:
        src: templates/kickstart.cfg.j2
        dest: "{{ role_path }}/files/{{ vm.name }}-kickstart.cfg"
        mode: '644'
    - name: Build kickstart iso
      ansible.builtin.shell:
        cmd: |
          set -o pipefail && $(ls /usr/local/bin/ | grep python | grep -v config) '{{ role_path }}/files/kickstart-iso.py' \
          '{{ role_path }}/files/{{ vm.name }}-kickstart.cfg' '{{ role_path }}/files/{{ vm.name }}-kickstart.iso'
        executable: /bin/bash
      register: build_kickstart_iso
      changed_when: build_kickstart_iso.rc == 0
