---
# Tasks to delete the nic1 gateway setting from interface file with self healing
- name: Delete GTW
  block:
    - include_tasks: task_delete_gtw_nic1.yml
  rescue:
    - include_tasks: task_delete_ssh_key.yml
    - include_tasks: task_delete_vm.yml
    - include_tasks: task_deploy_iso.yml
    - include_tasks: task_delete_gtw_nic1.yml
  always:
    - name: define gtw_rebuild
      ansible.builtin.set_fact:
        gtw_rebuild: "{{ delete_nic1gtw|default({'failed': false}) is failed }}"
    - name: check if rebuild is still required
      ansible.builtin.assert:
        that:
          - not gtw_rebuild|default(false)
        success_msg: 'Deleted the NIC1 gateway successfully'
        fail_msg: 'Unable to delete NIC1 gateway successfully'
  when:
    - netconfig.nic1.gateway == ''
    - netconfig.nic1.ipaddress != ''
    - netconfig.nic2.ipaddress != ''
  tags: vm_creation
