---
# Tasks to rollback VMs
- block:
  - block:
    - include_role:
        name: devsim
        tasks_from: task_stop_devsim
    - include_tasks: task_delete_vm.yml
    when:
      - not crecon | default(true) | bool
  - include_tasks:
      file: task_delete_folder.yml
      apply:
        vars:
          folder_name: "{{ fldr_name }}"
    when:
      - "'stack' in group_names"
      - inventory_hostname == ansible_play_hosts | intersect(groups['stack']) | first
      - hostvars[groups['vcenter'][0]]['information']['deptype'] == 'h'
  - include_tasks:
      file: task_delete_folder.yml
      apply:
        vars:
          folder_name: "{{ fldr_name }}"
    when:
      - build.disaster_recovery
      - "'dr' in group_names"
      - inventory_hostname == ansible_play_hosts | intersect(groups['dr']) | first
      - hostvars[groups['drvcenter'][0]]['information']['deptype'] == 'h'
