---
# Tasks to delete the VM folder
- block:
  - name: Get list of folders
    community.vmware.vmware_folder_info:
      hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
      username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
      password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
      datacenter_name: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
      validate_certs: no
    register: folder_info
    no_log: yes
  - block:
    - include_tasks: task_check_folder_empty.yml
    - ansible.builtin.debug:
        msg: "The folder '{{ folder_name }}' cannot be deleted because it is not empty"
      when: not folder_empty
    - block:
      - name: Delete the {{ folder_name }} folder
        community.vmware.vcenter_folder:
          hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
          username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
          password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
          datacenter_name: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
          folder_name: "{{ folder_name.split('/')[1:]|join('/') }}"
          folder_type: vm
          parent_folder: "{{ folder_name.split('/')|first }}"
          state: absent
          validate_certs: no
        register: cust_folder
      rescue:
      - ansible.builtin.fail:
          msg: "Failed to delete the folder '{{ folder_name }}'"
        when:
          - cust_folder is failed
      when: folder_empty
    when: folder_info.flat_folder_info|select('search', ffn)
    vars:
      ffn: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] + '/vm' + (('' if folder_name is regex('^/') else '/') + folder_name if folder_name != '' else '') }}"
  delegate_to: localhost
  run_once: yes
  tags: vm_creation
