---
# Tasks to disconnect the CDROM
- name: Disconnect CDROM
  community.vmware.vmware_guest:
    hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
    username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
    password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
    name: "{{ vm.name }}"
    datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
    cluster: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['cluster'] }}"
    folder: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] + '/vm' + \
      (('' if fldr_name is regex('^/') else '/') + fldr_name if fldr_name != '' else '') }}"
    validate_certs: false
    cdrom:
      - type: iso
        iso_path: "[{{ storage_ds if storage_ds != '' else vm_ds }}] {{ ('ISO/' + storage_path) if storage_path != '' else 'ISO' }}/{{ build.version.os_iso }}"
        controller_number: 0
        unit_number: 0
        state: absent
      - type: iso
        iso_path: "[{{ storage_ds if storage_ds != '' else vm_ds }}] {{ ('ISO/' + storage_path) if storage_path != '' else 'ISO' }}/{{ vm.name }}-kickstart.iso"
        controller_number: 1
        unit_number: 0
        state: absent
  ignore_errors: true # noqa: ignore-errors
  delegate_to: localhost
  environment:
    http_proxy: ''
    https_proxy: ''
  vars:
    storage_ds: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['storage_datastore'] }}"
    storage_path: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['storage_path'] }}"
