---
# tasks to set the folder name
- name: Define folder name
  ansible.builtin.set_fact:
    fldr_name: "{{ (('' if myfolder is regex('^/') else '/') + myfolder) if myfolder != '' else myfolder + '/' + mynameprefix }}"
  vars:
    myfolder: "{{ hostvars[inventory_hostname]['datacenter']['secondary' if 'dr' in group_names else 'primary']['folder'] }}"
    mynameprefix: "{{ hostvars[inventory_hostname]['build']['secondary' if 'dr' in group_names else 'primary']['name_prefix'] }}"
- name: Assert folder name is defined
  ansible.builtin.assert:
    that: fldr_name is defined
    success_msg: "{{ 'fldr_name is ' + fldr_name }}"
    fail_msg: 'fldr_name is not defined'
