---
# Tasks to create VM pairs
- name: Define vm_seq for each host
  ansible.builtin.set_fact:
    vm_seq: "{{ range(0, groups[vm_group] | length, 2) | list }}"

- name: Create configure
  ansible.builtin.include_tasks:
    file:
      task_create_configure_vms.yml
    apply:
      vars:
        pair_num: "{{ seq_item }}"
  loop: "{{ vm_seq }}"
  loop_control:
    loop_var: seq_item
  when:
    - inventory_hostname == groups[vm_group][seq_item] or ((groups[vm_group] | length - 1) >= (seq_item + 1) and \
      inventory_hostname == groups[vm_group][seq_item + 1])
