---
# Tasks to copy routes file to host
- name: Copy default route file to VM, attempt {{ try_num }}
  ansible.builtin.template:
    src: "templates/{{ 'dr' if 'dr' in group_names else '' }}route-ens160.tmpl"
    dest: "/etc/sysconfig/network-scripts/route-ens160"
    mode: '644'
  become: "{{ true if ansible_user != 'root' else false }}"
  ignore_errors: true # noqa: ignore-errors
- name: Verify content of route file, attempt {{ try_num }}
  ansible.builtin.command: grep -i address /etc/sysconfig/network-scripts/route-ens160
  register: copy_file_status
  changed_when: false
  ignore_errors: true
