---
# Tasks to rollback VMs
- name: Rollback VM
  vars:
    firsthost: "{{ ansible_play_hosts | intersect(groups['dr'] if 'dr' in group_names else groups['stack']) | first }}"
    inventory_folder: "{{ hostvars[inventory_hostname]['datacenter']['secondary' if 'dr' in group_names else 'primary']['folder'] }}"
    myfolder: "{{ ('/' if inventory_folder is not regex('^/') else '') + inventory_folder }}"
  block:
    - name: Stop devsim
      ansible.builtin.include_role:
        name: devsim
        tasks_from: task_stop_devsim
      when:
        - not crecon | default(true) | bool
    - name: Delete VM
      ansible.builtin.include_tasks: task_delete_vm.yml
    - name: Delete folder path
      ansible.builtin.include_tasks:
        file: task_delete_folder_path.yml
        apply:
          vars:
            curr_folder: "{{ myfolder }}"
      when:
        - inventory_hostname == firsthost
        - "'stack' in group_names"
        - inventory_hostname == ansible_play_hosts | intersect(groups['stack']) | first
        - hostvars[groups['vcenter'][0]]['information']['deptype'] == 'h'
    - name: Delete folder path
      ansible.builtin.include_tasks:
        file: task_delete_folder_path.yml
        apply:
          vars:
            curr_folder: "{{ myfolder }}"
      when:
        - build.disaster_recovery
        - inventory_hostname == firsthost
        - "'dr' in group_names"
        - inventory_hostname == ansible_play_hosts | intersect(groups['dr']) | first
        - hostvars[groups['drvcenter'][0]]['information']['deptype'] == 'h'
