---
# Tasks to create the kickstart ISO
- block:
  - name: Create kickstart cfg
    ansible.builtin.template:
      src: templates/kickstart.cfg.j2
      dest: "{{ role_path }}/files/{{ vm.name }}-kickstart.cfg"
  - name: Build kickstart iso
    ansible.builtin.shell: $(ls /usr/local/bin/|grep python|grep -v config) '{{ role_path }}/files/kickstart-iso.py' '{{ role_path }}/files/{{ vm.name }}-kickstart.cfg' '{{ role_path }}/files/{{ vm.name }}-kickstart.iso'
  delegate_to: localhost
