---
# tasks to determine whether or not the folder is empty
- name: Checking if folder is empty
  block:
    - name: Get the{{ (' DR' if (drvm_names is defined and vm_name in drvm_names) else '') + ' VMs in ' + folder_name }}
      community.vmware.vmware_vm_info:
        hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
        username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
        password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
        folder: "{{ '/' + hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] + '/vm' + foldername }}"
        show_net: false
        validate_certs: false
      check_mode: false
      register: vm_info
      delegate_to: localhost
    - name: Define folder_empty
      ansible.builtin.set_fact:
        folder_empty: "{{ vm_info.virtual_machines == [] }}"
  rescue:
    - name: Debug message
      ansible.builtin.debug:
        msg:
          - "{{ vm_info }}"
