---
# Tasks to create and configure VM pairs
- block:
  - include_tasks: task_get_vm_datastore.yml
    when:
      - hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datastore_cluster'] == '' or hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['deptype'] == 'h'
  - block:
    - include_tasks: task_create_kickstart_iso.yml
    - include_tasks: task_copy_kickstart_iso_to_vsphere.yml
    - include_tasks: task_deploy_iso_self_healing.yml
    when:
      - crecon | default(true) | bool
      - "vcr_vm_reachable|default({'failed': true}) is skipped or vcr_vm_reachable|default({'failed': true}) is failed"
      - "vcr_vm_connection|default({'failed': true}) is skipped or vcr_vm_connection|default({'failed': true}) is failed"
  - include_tasks: task_update_custom_attributes.yml
  - include_tasks: task_delete_gtw_nic1_self_healing.yml
  - include_tasks: task_update_disks_self_healing.yml
  - block:
    - include_tasks: task_poweroff_vm.yml
    - include_tasks: task_disconnect_cdrom.yml
    - include_tasks: task_poweron_vm.yml
    - include_tasks: task_delete_kickstart_files.yml
    - include_tasks: task_update_default_route.yml
    - include_tasks: task_add_gtw2.yml
    - include_tasks: task_increase_open_files_limit.yml
    when:
      - crecon | default(true) | bool
      - "vcr_vm_reachable|default({'failed': true}) is skipped or vcr_vm_reachable|default({'failed': true}) is failed"
      - "vcr_vm_connection|default({'failed': true}) is skipped or vcr_vm_connection|default({'failed': true}) is failed"
  - block:
    - name: check disks order
      ansible.builtin.shell: |
        df -h | grep /boot | awk '{print $1}'
      register: reg_boot
      become: "{{ true if ansible_user != 'root' else false }}"
    - name: reboot vm
      ansible.builtin.reboot:
        post_reboot_delay: 10
        reboot_timeout: 60
      when: reg_boot.stdout is not search('sda')
      become: "{{ true if ansible_user != 'root' else false }}"
    when:
      - vmguest_disk0 is changed or vmguest_disk1 is changed or vmguest_disk2 is changed or vmguest_disk3 is changed
      - disk_info.guest_disk_info | dict2items | length >= 2
  - name: flush handlers
    meta: flush_handlers
  - include_tasks: task_increase_max_pid_number.yml
