---
# tasks to increase the maximum number of PID
- name: increase max PID number
  ansible.posix.sysctl:
    name: kernel.pid_max
    value: '100000'
    sysctl_set: true
    reload: true
  tags: vm_ccreation
