---
# Tasks to copy the ISO file to datastore
- name: Copying ISO to Vsphere
  vars:
    mystorage_ds: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['storage_datastore'] }}"
    mystorage_path: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['storage_path'] }}"
  delegate_to: localhost
  block:
    - name: Define iso_datastore and iso_path
      ansible.builtin.set_fact:
        iso_datastore: "{{ mystorage_ds if mystorage_ds != '' else vm_ds }}"
        iso_path: "ISO{{ '/' + mystorage_path if mystorage_path != '' else '' }}"
    - name: Create a directory on the datastore
      community.vmware.vsphere_file:
        hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
        username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
        password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
        datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
        datastore: "{{ iso_datastore }}"
        path: "{{ iso_path }}"
        state: directory
        validate_certs: false
      register: ds_folder
      throttle: 1
    - name: Copying ISO files to Vsphere
      when: ds_folder is succeeded
      vars:
        firsthost: "{{ ansible_play_hosts | intersect(groups['dr'] if 'dr' in group_names else groups['stack']) | first }}"
        mydeptype: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['deptype'] }}"
      block:
        - name: Poweroff VM
          ansible.builtin.include_tasks: task_poweroff_vm.yml
        - name: Copy kickstart ISO file to vsphere
          community.vmware.vsphere_copy:
            hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
            username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
            password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
            datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
            datastore: "{{ iso_datastore }}"
            src: "{{ role_path }}/files/{{ vm.name }}-kickstart.iso"
            path: "{{ iso_path }}/{{ vm.name }}-kickstart.iso"
            validate_certs: false
        - name: Copy ISO to Vsphere
          ansible.builtin.include_tasks: task_copy_iso_to_vsphere.yml
          when:
            - mycondition
          vars:
            mycondition: "{{ inventory_hostname == firsthost if mydeptype is search('h') else inventory_hostname in ansible_play_hosts }}"
        - name: Wait for ISO to be copied to vsphere
          ansible.builtin.wait_for:
            path: "/var/tmp/{{ 'secondary' if 'dr' in group_names else 'primary' }}_iso_copy_complete.txt"
            state: present
            timeout: 1200
            delay: 10
            sleep: 30
          when:
            - hostvars[firsthost]['iso_present'] is not defined or hostvars[firsthost]['iso_present'] is failed
            - mycondition
          vars:
            mycondition: "{{ inventory_hostname != firsthost if mydeptype is search('h') else false }}"
