---
# Tasks to create and configure VM pairs
- block:
  - include_tasks: task_get_vm_datastore.yml
    when:
      - hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datastore_cluster'] == ''

  - include_tasks: task_create_kickstart_iso.yml
  - include_tasks: task_copy_kickstart_iso_to_vsphere.yml
  - include_tasks: task_deploy_iso_self_healing.yml
  - include_tasks: task_update_custom_attributes.yml
  - include_tasks: task_delete_gtw_nic1_self_healing.yml
  - include_tasks: task_update_disks_self_healing.yml
  - include_tasks: task_delete_kickstart_files.yml
  - include_tasks: task_update_default_route.yml
  - include_tasks: task_add_gtw2.yml
  - include_tasks: task_increase_open_files_limit.yml

  - name: flush handlers
    meta: flush_handlers

  - include_tasks: task_increase_max_pid_number.yml
  - include_tasks: task_update_os.yml
  tags: vm_creation
