---
# Task file to create forward DNS record
- name: Create forward DNS record
  delegate_to: localhost
  vars:
    mydc: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
  block:
    - name: Add {{ mydesignation + ' DNS record' }}
      ansible.builtin.shell: |
        {% if mydc is search('-HX-DC') %}
        sshpass -p {{ svc_password }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -T -l {{ svc_username }} {{ lookup('env', 'MYIP') }} <<EOF
        {% endif %}
        nsupdate {% if mydc is search('-HX-DC') %}-g {% endif %}<<EOC
        server {{ myserver }}
        update add {{ myrecord }}.{{ mydomain }} 86400 A {{ myipaddress }}
        send
        EOC
        {% if mydc is search('-HX-DC') %}
        EOF
        {% endif %}
      register: reg_fdr
      changed_when: reg_fdr.rc == 0
      failed_when: reg_fdr.rc != 0 and reg_fdr.stderr is not search('tsig verify failure')
      until: reg_fdr is succeeded
      delay: 10
      no_log: true
  rescue:
    - name: Debug message
      ansible.builtin.debug:
        msg: "{{ reg_fdr | replace(svc_password, 'obfuscated') if svc_password != '' else reg_fdr }}"
  always:
    - name: Assert that creating forward DNS record succeeded
      ansible.builtin.assert:
        that: reg_fdr is succeeded
