---
# Task file to delete DNS records
- name: Delete primary site records
  when:
    - "'stack' in group_names"
  block:
    - name: Delete forward record
      ansible.builtin.include_tasks:
        file: task_delete_forward_record.yml
        apply:
          vars:
            mydesignation: 'primary'
            myserver: "{{ sysconfig.primary.dns_servers[0] }}"
            mydomain: "{{ sysconfig.primary.domain_name }}"
            myrecord: "{{ vm.name }}"
            myipaddress: "{{ netconfig.nic1.ipaddress if vm.name is not search('csr') else netconfig.nic3.ipaddress }}"
    - name: Delete reverse record
      ansible.builtin.include_tasks:
        file: task_delete_reverse_record.yml
        apply:
          vars:
            mydesignation: 'primary'
            myserver: "{{ sysconfig.primary.dns_servers[0] }}"
            mydomain: "{{ sysconfig.primary.domain_name }}"
            myrecord: "{{ vm.name }}"
            myipaddress: "{{ netconfig.nic1.ipaddress if vm.name is not search('csr') else netconfig.nic3.ipaddress }}"
- name: Delete secondary site records
  when:
    - build.disaster_recovery
    - "'dr' in group_names"
  block:
    - name: Delete forward record
      ansible.builtin.include_tasks:
        file: task_delete_forward_record.yml
        apply:
          vars:
            mydesignation: 'secondary'
            myserver: "{{ sysconfig.secondary.dns_servers[0] }}"
            mydomain: "{{ sysconfig.secondary.domain_name }}"
            myrecord: "{{ vm.name }}"
            myipaddress: "{{ netconfig.nic1.ipaddress if vm.name is not search('csr') else netconfig.nic3.ipaddress }}"
    - name: Delete reverse record
      ansible.builtin.include_tasks:
        file: task_delete_reverse_record.yml
        apply:
          vars:
            mydesignation: 'secondary'
            myserver: "{{ sysconfig.secondary.dns_servers[0] }}"
            mydomain: "{{ sysconfig.secondary.domain_name }}"
            myrecord: "{{ vm.name }}"
            myipaddress: "{{ netconfig.nic1.ipaddress if vm.name is not search('csr') else netconfig.nic3.ipaddress }}"
