---
# tasks file for vm_configuration
- block:
  - name: check original credentials
    block:
      - name: check VM credentials
        wait_for_connection:
          timeout: 3
        register: vco_vm_creds
        check_mode: no
    rescue:
      - name: define creds_status
        ansible.builtin.set_fact:
          creds_status: 'The VM IP address is invalid'
        when:
          - vco_vm_creds.msg is search('Failed to connect to the host via ssh')
      - block:
        - name: check service account credentials
          block:
            - name: Switch to {{ vm_svc_user }} user
              set_fact:
                ansible_user: "{{ vm_svc_user }}"
                ansible_ssh_pass: "{{ vm_svc_pass }}"
                ansible_become_pass: "{{ vm_svc_pass }}"
              no_log: true
            - name: check updated VM credentials
              wait_for_connection:
                timeout: 3
              check_mode: no
          rescue:
            - name: define creds_status
              ansible.builtin.set_fact:
                creds_status: 'The VM credentials are invalid'
        when:
          - vco_vm_creds.msg is search('Invalid/incorrect')
  - assert:
      that:
        - creds_status | default('') is not search('invalid')
      fail_msg: "{{ creds_status | default('') }}"

  - include_tasks: task_configure_vms.yml
  when: configure_vms_iso | default(false) | bool
  tags: vm_configuration
