---
# tasks file to configure_vms
- name: Get repo credentials
  ansible.builtin.include_tasks: task_get_repo_creds.yml
- name: Get simulator
  ansible.builtin.include_tasks: task_get_simulator.yml
- name: Stop services
  ansible.builtin.include_tasks: task_stop_services.yml
- name: Add static route
  ansible.builtin.include_tasks: task_add_static_route.yml
- name: Enable SSH support
  ansible.builtin.include_tasks: task_enable_ssh_support.yml
