---
# tasks to enable SSH support
- name: Add VM's IP to sshd_config
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^#(ListenAddress) 0\.0\.0\.0'
    replace: '\g<1> {{ ansible_host }}'
  notify: Restart sshd service
  become: "{{ true if ansible_user != 'root' else false }}"
