---
# Tasks file to manage service
- block:
  - name: "{{ 'stop' if action is search('stop') else 'start' }} {{ service }}"
    ansible.builtin.systemd:
      name: "{{ service }}"
      state: "{{ action }}"
      enabled: "{{ state }}"
    become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_configuration
