---
# Tasks file to stop services
- block:
  - include_tasks:
      file: task_manage_service.yml
      apply:
        vars:
          service: "{{ service_item }}"
          action: 'stopped'
          state: 'false'
    loop:
      - firewalld
      - iptables
    loop_control:
      loop_var: service_item      
  tags: vm_configuration
