---
# Tasks file to manage service
- name: "{{ ('Stop' if action is search('stop') else 'Start') + ' service' }}"
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: "{{ action }}"
    enabled: "{{ state }}"
  become: "{{ true if ansible_user != 'root' else false }}"
