---
# vars file for vm_fromiso
chrony_file: '/etc/chrony.conf'
iso_dir: 'Packages/ISO'
iso_installer: "{{ build.version.os_iso }}"
vm_app_user: "{{ user.name if user.name != '' else vars[('S' if 'dr' in group_names else 'P') + 'APPADMIN_USER'] }}"
vm_app_pass: "{{ user.password if user.name != '' else vars[('S' if 'dr' in group_names else 'P') + 'APPADMIN_PASS'] }}"
