---
# vars file for vm_fromiso
iso_dir: 'Packages/ISO'
iso_installer: "{{ build.version.os_iso }}"
vm_svc_user: "{{ user.name if user.name != '' else vars[('S' if 'dr' in group_names else 'P') + 'SVC_USER'] if credentials.username == 'root' else credentials.username }}"
vm_svc_pass: "{{ user.password if user.name != '' else credentials.password }}"
chrony_file: '/etc/chrony.conf'
