---
# vars file for vm_hardening
vm_app_user: "{{ user.name if user.name != '' else vars[('S' if 'dr' in group_names else 'P') + 'LINUX_APPADMIN_USER'] }}"
vm_app_pass: "{{ user.password if user.name != '' else vars[('S' if 'dr' in group_names else 'P') + 'LINUX_APPADMIN_PASS'] }}"
hardening_site: 'https://wwwin-github.cisco.com/sto-ccc'
hardening_reponame: 'ansible-os_hardening'
