---
# Validate credentials (always run)
- name: Validate credentials
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: false

  roles:
    - role: check_creds

# Play to determine what to do and to define vm facts(always run)
- name: Define variables
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: false

  roles:
    - role: todo
    - role: vm_facts

# Play to perform the infrastructure capacity check
- name: Pre-deploy preparation
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: false

  tasks:
    - name: Preparation
      when: deploy | default(false) | bool
      block:
        - name: Capcheck
          ansible.builtin.include_role:
            name: capcheck
          when: capcheck | default(false) | bool
          tags: ['capcheck', 'vm_creation']
        - name: Infra DNS records
          ansible.builtin.include_role:
            name: infra_dns_records
          when: add_dns_records | default(false) | bool
          tags: ['infra_dns_records', 'vm_creation']

# Play to create the VMs
- name: Deploy VMs
  hosts: all
  strategy: free # noqa: run-once[play]
  gather_facts: false

  tasks:
    - name: Deploy
      when: deploy | default(false) | bool
      block:
        - name: VM from ISO
          ansible.builtin.include_role:
            name: vm_fromiso
          when: create_vms_iso | default(false) | bool
          tags: vm_creation

# Play to configure the VMs
- name: Configure VMs
  hosts: all
  gather_facts: false

  tasks:
    - name: Configure VM
      when: deploy | default(false) | bool
      block:
        - name: VM hardening
          ansible.builtin.include_role:
            name: vm_hardening
          when: harden_vms | default(false) | bool
          tags: vm_hardening
        - name: VM from ISO configuration
          ansible.builtin.include_role:
            name: vm_configuration_iso
          when: configure_vms_iso | default(false) | bool
          tags: vm_configuration

# Play to manage the device simulator
- name: Device Simulator Management
  hosts: all
  gather_facts: false

  tasks:
    # yamllint disable rule:line-length
    - name: Device simulator management
      when: deploy | default(false) | bool or start | default(false) | bool or check | default(false) | bool or stop | default(false) | bool or rollback | default(false) | bool
      block:
        - name: Devsim
          ansible.builtin.include_role:
            name: devsim
          when: deploy_devsim | default(false) | bool or start_devsim | default(false) | bool or check_devsim | default(false) | bool or stop_devsim | default(false) | bool or rollback_devsim | default(false) | bool
          tags: ['never', 'devsim']
    # yamllint enable rule:line-length

# Play to delete the VMs
- name: Rollback VMs
  hosts: all
  order: reverse_inventory
  gather_facts: false

  tasks:
    - name: Rollback
      when: rollback | default(false) | bool
      block:
        - name: VM from ISO
          ansible.builtin.include_role:
            name: vm_fromiso
          when: rollback_vms_iso | default(false) | bool
          tags: vm_creation
        - name: Infra DNS records
          ansible.builtin.include_role:
            name: infra_dns_records
          when: rollback_dns_records | default(false) | bool
          tags: ['infra_dns_records', 'vm_creation']
